@startuml

class Main
{

}

class Ordinateur
{

}

class Joueur
{
# m_num : Integer
# m_pseudo : String
# m_pioche : Pokemon[*]
# m_main : Pokemon[*]
# m_defausse : Pokemon[*]
# m_terrain : Pokemon[*]
+ <<Create>> Joueur(pseudo: String, ordrePassage: Integer)
+ piocher()
+ placerPokemon()

}




class Plateau
{
+ afficherPlateau()
+afficherFinDuJeu()
}

class Gestion_Tour
{

}

package "Create_Pokemon" #DDDDDD {

class Pokemon
{
- m_nom : String
- m_pv : Integer
- m_attaque : Integer
+ <<Create>> Pokemon()
+ attaque(autre : Pokemon)
+ getNom() : String
+ toString() : String
}



class Initialisation
{
- m_listeNoms : String[*]
- m_index : Integer
+ getNom() : String
}

class Element
{
- m_avantage : String
- m_desavantage : String
- m_nom : String
+ <<Create>> Element (nom : String)
+ getElement() : String
+ getAvantage() : String
+ getDesavantage() : String
}

}

Plateau --> Pokemon
Pokemon --|> "- m_element" Element
Ordinateur --> Joueur
Joueur --> Plateau
Main --> Pokemon
Main --> Joueur
Pokemon --|> Initialisation


@enduml