@startuml

class Main
{

}

class Ordinateur
{

}

class Joueur
{
# m_num : Integer
# m_pseudo : String
# m_pioche : ArrayList<Pokemon>
# m_main : ArrayList<Pokemon>
# m_defausse : ArrayList<Pokemon>
# m_terrain : ArrayList<Pokemon>
+ "create" Joueur(pseudo: String, ordrePassage: Integer)
+ piocher():Void
+ placerPokemon():Void

}




class Plateau
{
+ afficherPlateau(): Void
+afficherFinDuJeu(): Void
}


package "Create_Pokemon" #DDDDDD {

class Pokemon
{
- m_nom : String
- m_pv : Integer
- m_attaque : Integer
- m_element : Element
+ <<Create>> Pokemon ()
+ attaque(autre : Pokemon)
+ getNom() : String
+ toString() : String
}

class Initialisation
{
- m_listeNoms : ArrayList<String>
- m_index : Integer
+ getNom() : String
}

class Element
{
- m_avantage : String
- m_desavantage : String
- m_nom : String
+ <<Create>> Element (nom : String)
+ getElement() : String
+ getAvantage() : String
+ getDesavantage() : String
}

}

Plateau --> Pokemon
Pokemon --> Element
Ordinateur --> Joueur
Joueur --> Plateau
Main --> Pokemon
Main --> Joueur
Pokemon --> Initialisation


@enduml